apiVersion: v1
kind: Secret
metadata:
  name: agora-secret
  namespace: healthcare
type: Opaque
stringData:
  AGORA_APP_ID: "0285c138d0d34d71ba6b7a6a0440cc1b"
  AGORA_APP_CERTIFICATE: "a26ef39826a24a3599b281f64b60207f"
