server:
  port: 8088

spring:
  application:
    name: notification-service

  # MySQL Database Configuration (docker-compose)
  datasource:
    url: jdbc:mysql://mysql-notification:3306/notification_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  # Email Configuration (Gmail)
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
            protocols: TLSv1.2
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

# Twilio Configuration (WhatsApp)
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  whatsapp-number: ${TWILIO_WHATSAPP_NUMBER}

# Eureka
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

logging:
  level:
    com.healthcare.notification_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info