server:
  port: 8084

spring:

  application:
    name: appointment-service

  datasource:
    url: jdbc:mysql://mysql-appointment:3306/appointment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: appointment-service

logging:
  level:
    com.healthcare.appointment_service: INFO