apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
  namespace: healthcare
  labels:
    app: telemedicine-service
spec:
  selector:
    app: telemedicine-service
  ports:
  - port: 8085
    targetPort: 8085
  type: LoadBalancer
