server:
  port: 8082

spring:
  application:
    name: patient-service
  
  # Database Configuration - For Docker (MySQL in container)
  datasource:
    url: jdbc:mysql://mysql-patient:3306/patient_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2KB

# Disable Eureka for now
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: patient-service

# Cloudinary Configuration
cloudinary:
  cloud-name: dwona3xzj
  api-key: 541144828641826
  api-secret: RoOFJQi-nLfT0_ExZewiJ_TsOak

# File Storage Configuration
app:
  storage:
    type: cloudinary
  file:
    upload-dir: ./uploads/patients
  base-url: http://localhost:8082

# Logging
logging:
  level:
    com.healthcare.patient_service: INFO